check/urls.py
from django.urls import path
from .views import show_check, create_check, update_check, delete_check, debug

urlpatterns = [
    path('overview', show_check, name='show_check'),
    path('new', create_check, name='create_check'),
    path('update/<int:id>/', update_check, name='update_check'),
    path('delete/<int:id>/', delete_check, name='delete_check'),

    path('debug', debug, name='debug'),

]

siteisrunning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from siteisrunning.views import redirect_view, term_condition_privacy, contact, home, what

urlpatterns = [
    path('admin/', admin.site.urls),
    path('redirect/', redirect_view),

    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('payment.urls')),

    path('', home, name='home'),
    path('websites/', include('check.urls')),
    path('terms-condition-privacy/', term_condition_privacy, name='term_condition_privacy'),
    path('contact/', contact, name='contact'),
    path('what/', what, name='what'),

    path('robots.txt/', TemplateView.as_view(template_name='base/robots.txt', content_type='text/plain'),
         name='robots'),

]

users/urls.py
from django.conf.urls import url
from django.urls import include, path

from .views import update_account, delete_account

urlpatterns = [
    url(r"^update/$", update_account, name='update_account'),
    url(r"^delete/$", delete_account, name='delete_account')
]

users/models.py
# users/models.py
import pytz
from allauth.account.models import EmailAddress
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.apps import apps


class CustomUser(AbstractUser):
    # add additional fields in here
    company = models.TextField(blank=True)
    timezone = models.CharField(max_length=40, null=True, blank=True, choices=[(n, n) for n in pytz.all_timezones])

    def __str__(self):
        return self.email

    def is_paying(self):
        payment_model = apps.get_model('payment', 'Payment')
        if payment_model.objects.filter(owner_id=self.id).exists():
            payment = payment_model.objects.get(owner_id=self.id)
            if not payment.is_user_paying_expired():
                return True

        return False

    def payment_attributes_for_render(self):
        payment_model = apps.get_model('payment', 'Payment')
        is_user_paying = False
        payment_id = None
        payment_expires_at = None
        expires_reminder_sent_at = None

        if payment_model.is_user_paying(self):
            payment = payment_model.objects.get(owner_id=self.id)
            if not payment.is_user_paying_expired():
                is_user_paying = True
                payment_id = payment.id
                payment_expires_at = payment.payment_expires_at.strftime("%Y/%m/%d")
                expires_reminder_sent_at = payment.expires_reminder_sent_at.strftime("%Y/%m/%d")

        return {
            "is_user_paying": is_user_paying,
            "payment_id": payment_id,
            "payment_expires_at": payment_expires_at,
            "expires_reminder_sent_at": expires_reminder_sent_at,
        }

users/forms.py
import pytz
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django import forms

from django.contrib.auth import get_user_model

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    company = forms.CharField(required=False)
    accept_term = forms.BooleanField(required=True)
    timezone = forms.ChoiceField(required=False, choices=[(t, t) for t in pytz.common_timezones])
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox(attrs={
        'data-theme': 'white',
        'data-size': 'normal',
    }))

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'company']

    def signup(self, request, user):
        user.company = self.cleaned_data['company']
        user.timezone = 'GMT'
        user.save()


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'company', 'timezone']

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from users.forms import CustomUserChangeForm

User = get_user_model()


@login_required
def update_account(request):
    form = CustomUserChangeForm(request.POST or None, instance=request.user)
    if form.is_valid():
        user = request.user
        user.save()
        messages.success(request, 'Account updated successfully')
        return redirect('update_account')

    return render(request, 'update_account_form.html', {'form': form})


@login_required
def delete_account(request):
    if request.method == 'POST':
        user = request.user
        user.is_active = False
        user.save()
        user.delete()
        messages.success(request, 'Account deleted successfully')
        return redirect('delete_account')

    return render(request, 'delete_account_form.html')

users/templates/delete_account_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Delete Account{% endblock %}
{% block metatitle %}Delete Account{% endblock %}
{% block metadescription %}Do you really want delete your Account? :( {% endblock %}

{% block nav %}
    {% include 'base/_nav.html' %}
{% endblock %}

{% block content %}
    {% include "base/_small_header.html" %}
    {% include "account/_tabs.html" %}

    <section class="m-t-40 sm-m-t-30">

        <section class="p-b-10">
            <div class="container">
                <div class="">
                    <h1 class="text-center">Delete Account</h1>
                </div>
            </div>
        </section>

        <section class="p-b-40">
            <div class="container">
                <div class="m-b-30 with-border padding-20 text-center">

                    <form method="POST">
                        {% csrf_token %}
                        <p class="fs-18">Are you sure to delete the Account?</p>
                        <button class="m-t-15 btn btn-danger" type="submit">DELETE</button>
                    </form>

                </div>
            </div>
        </section>

    </section>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
        });
    </script>
{% endblock %}

users/templates/update_account_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Update Account{% endblock %}
{% block metatitle %}Update Account{% endblock %}
{% block metadescription %}Edit your account here{% endblock %}

{% block nav %}
    {% include 'base/_nav.html' %}
{% endblock %}

{% block content %}
    {% include "base/_small_header.html" %}
    {% include "account/_tabs.html" %}

    <section class="m-t-40 sm-m-t-30">

        <section class="p-b-10">
            <div class="container">
                <div class="">
                    <h1 class="text-center">Update Account</h1>
                </div>
            </div>
        </section>

        <section class="p-b-40">
            <div class="container">
                <div class="m-b-30 with-border padding-20 col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">


                    <form method="POST" id="create-edit-form">
                        <div class="form-group">
                            {% include 'base/_messages.html' %}
                            {% csrf_token %}

                            <div class="form-group form-group-default required">
                                <label class="control-label" for="id_password">Username</label>
                                {{ form.username|add_class:'form-control' }}
                            </div>


                            <div class="form-group form-group-default">
                                <label class="control-label" for="id_company">Company</label>
                                {{ form.company|add_class:'form-control' }}
                            </div>

                            <div class="form-group form-group-default required">
                                <label class="control-label" for="id_timezone">Timezone</label>
                                {{ form.timezone }}
                            </div>

                            <div class="form-group form-group-default">
                                {% if user.is_paying %}
                                    Pro Plan => expires at
                                    {{ user.payment_attributes_for_render.payment_expires_at }}
                                {% else %}
                                    Basic Plan => <a href="{% url 'checkout_account' %}">Upgrade to Pro Plan</a>
                                {% endif %}
                            </div>

                            <div class="form-group form-group-default">
                                <label class="control-label" for="id_password"><a href="{% url 'account_email' %}">Change
                                    Email</a></label>
                            </div>

                            <div class="form-group form-group-default">
                                <label class="control-label" for="id_password">
                                    <a href="{% url 'account_change_password' %}">Change Password</a>
                                </label>
                            </div>

                            <div class="m-t-20">
                                <button class="btn btn-primary m-r-75" type="submit">Save</button>

                                <a href="{% url 'delete_account' %}" class="btn btn-danger text-light">Delete
                                    Account</a>
                            </div>

                        </div>
                    </form>

                </div>
            </div>
        </section>

    </section>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#create-edit-form').validate();
        });
    </script>
{% endblock %}