check/urls.py
from django.urls import path
from .views import show_check, create_check, update_check, delete_check, debug

urlpatterns = [
    path('overview', show_check, name='show_check'),
    path('new', create_check, name='create_check'),
    path('update/<int:id>/', update_check, name='update_check'),
    path('delete/<int:id>/', delete_check, name='delete_check'),

    path('debug', debug, name='debug'),

]

siteisrunning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from siteisrunning.views import redirect_view, term_condition_privacy, contact, home, what

urlpatterns = [
    path('admin/', admin.site.urls),
    path('redirect/', redirect_view),

    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('payment.urls')),

    path('', home, name='home'),
    path('websites/', include('check.urls')),
    path('terms-condition-privacy/', term_condition_privacy, name='term_condition_privacy'),
    path('contact/', contact, name='contact'),
    path('what/', what, name='what'),

    path('robots.txt/', TemplateView.as_view(template_name='base/robots.txt', content_type='text/plain'),
         name='robots'),

]

siteisrunning/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3, ReCaptchaV2Checkbox
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}), required=True)
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox(attrs={
        'data-theme': 'white',
        'data-size': 'normal',
    }))

templates/base/_footer.html
{% load static %}
{% load staticfiles %}

<!-- BEGIN FOOTER -->
<footer class="p-b-25 p-t-50 xs-p-b-20 bg-master-darker ">
    <div class="container">
        <div class="row">
            <div class="col-sm-3 col-xs-12 xs-m-b-40">
                <a href="{% url 'home' %}">
                    <div class="slogan-calling text-white">
                        <span id="first">site</span>
                        <span id="second">isrunning.com</span>
                    </div>
                </a>
            </div>
            <div class="col-sm-3 col-xs-6 xs-m-b-20">
                <h6 class="font-montserrat text-uppercase fs-14 text-white p-b-10">About</h6>
                <ul class="no-style">
                    <li class="m-b-5 no-padding"><a href="/#price" class="link text-white">Pricing</a></li>
                    <li class="m-b-5 no-padding"><a href="{% url 'contact' %}" class="link text-white">Contact</a></li>

                </ul>
            </div>
            <div class="col-sm-3 col-xs-6 xs-m-b-20">
                <h6 class="font-montserrat text-uppercase fs-14 text-white p-b-10">Others</h6>
                <ul class="no-style">
                    <li class="m-b-5 no-padding"><a href="{% url 'what' %}" class="link text-white">FAQ</a></li>
                    <li class="m-b-5 no-padding"><a href="{% url 'term_condition_privacy' %}" class="link text-white">Privacy/Terms/Condition</a>
                    </li>
                </ul>
            </div>
        </div>
        <p class="fs-12 hint-text p-t-10 text-white">Copyright &copy;
            <script>document.write(new Date().getFullYear())</script>
            All Rights Reserved
        </p>
    </div>
</footer>
<!-- END FOOTER -->

templates/base/_messages.html
{% load static %}
{% load staticfiles %}
<section class="clearfix messages-and-and-alerts">
    {% for message in messages %}
        <div class="col-md-8 col-md-offset-2 alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="
                    background: url({% static 'assets/icons/noti-cross.png' %}) no-repeat scroll 0 0 transparent">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
    {% if form.non_field_errors or form.errors %}
        <div class="alert alert-danger">
            {{ form.non_field_errors }}

            {% if form.errors %}
                <ul class="alert alert-danger">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>
                                {% if field != '__all__' %}
                                    <strong>{{ field.label }}:</strong>
                                {% endif %}
                                {{ error }}
                            </li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    {% endif %}
</section>

templates/base/_nav.html
{% load static %}
{% load staticfiles %}

{% if request.resolver_match.url_name == 'home' %}
    <nav class="header bg-header transparent-dark " data-pages="header"
         data-pages-header="autoresize" data-pages-resize-class="dark">
{% else %}
    <nav class="position-unset header bg-header minimized dark">
{% endif %}


{#<nav style="position: unset !important;" class="header bg-header transparent-dark " data-pages="header"#}
{#     data-pages-header="autoresize" data-pages-resize-class="dark">#}
<div class="container relative">
    <!-- BEGIN LEFT CONTENT -->
    <div class="pull-left">
        <!-- .header-inner Allows to vertically Align elements to the Center-->
        <div class="header-inner">
            <!-- BEGIN LOGO -->
            <a href="{% url 'home' %}">
                <div class="slogan-calling text-white">
                    <span id="first">site</span>
                    <span id="second">isrunning.com</span>
                </div>
            </a>
        </div>
    </div>
    <!-- BEGIN HEADER TOGGLE FOR MOBILE & TABLET -->
    <div class="pull-right">
        <div class="header-inner">
            <div class="visible-sm-inline visible-xs-inline menu-toggler pull-right p-l-10"
                 data-pages="header-toggle" data-pages-element="#header">
                <div class="one"></div>
                <div class="two"></div>
                <div class="three"></div>
            </div>
        </div>
    </div>
    <!-- END HEADER TOGGLE FOR MOBILE & TABLET -->
    <!-- BEGIN RIGHT CONTENT -->
    <div class="menu-content mobile-dark pull-right clearfix" data-pages-direction="slideRight" id="header">
        <!-- BEGIN HEADER CLOSE TOGGLE FOR MOBILE -->
        <div class="pull-right">
            <a href="#" class="padding-10 visible-xs-inline visible-sm-inline pull-right m-t-10 m-b-10 m-r-5"
               data-pages="header-toggle" data-pages-element="#header">
                <i class=" pg-close_line"></i>
            </a>
        </div>
        <!-- END HEADER CLOSE TOGGLE FOR MOBILE -->
        <!-- BEGIN MENU ITEMS -->
        <div class="header-inner">
            <ul class="menu">
                <li>
                    <a href="/" {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}>Home</a>
                </li>

                <li>
                    <a href="/#price">Pricing</a>
                </li>

                <li>
                    <a href="{% url 'what' %}"
                       {% if request.resolver_match.url_name == 'what' %}class="active"{% endif %}>What</a>
                </li>

                <li class="hidden-sm hidden-xs">
                    <a href="">|</a>
                </li>

                <li class="hidden-md hidden-lg col-xs-offset-1">
                    <div>--------------------------------</div>
                </li>

                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'show_check' %}"
                                {% if '/accounts/' in request.path or '/websites/' in request.path %}
                           class="active"{% endif %}>Account
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'account_login' %}"
                           {% if request.resolver_match.url_name == 'account_login' %}class="active"{% endif %}>Login</a>
                    </li>

                    <li>
                        <a href="{% url 'account_signup' %}"
                           {% if request.resolver_match.url_name == 'account_signup' %}class="active"{% endif %}>Sign
                            Up</a>
                    </li>
                {% endif %}
            </ul>
            <!-- FOR MOBILE -->
            <div class="font-arial m-l-35 m-r-35 m-b-20 visible-sm visible-xs m-t-20">
                <p class="fs-11 no-margin small-text p-b-20">You're in the right place here.</p>
            </div>
            <!-- END FOR MOBILE -->
        </div>
        <!-- END MENU ITEMS -->
    </div>
</div>
</nav>

templates/base/_small_header.html
{% load staticfiles %}
{% load static %}

<section class="p-t-50 p-b-50 m-b-50 bg-master-darkest"
         style="background-image: url('{% static "assets/images/mountains-1246683.jpg" %}'); background-position: 80% 65% !important;">
    <div class="container">
        <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
            <div class="text-center">
                <h3 class="text-white col-sm-12">You're in good hands.</h3>
            </div>
        </div>
    </div>
</section>

templates/base/base.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% if not debug %}
        <!-- Google Tag Manager -->
        <script>(function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-NCK9FJK');</script>
        <!-- End Google Tag Manager -->
    {% endif %}


    <meta http-equiv="content-type" content="text/html;charset=UTF-8">
    <meta charset="utf-8">

    <title>{% spaceless %}{% block title %}{% endblock %}{% endspaceless %} - siteisrunning.com</title>
    <meta content="{% spaceless %}{% block metadescription %}{% endblock %}{% endspaceless %}" name="description"/>
    <meta content="{% spaceless %}{% block metatitle %}{% endblock %}{% endspaceless %}" name="title">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    {#    <link rel="apple-touch-icon" href="pages/ico/60.png">#}
    {#    <link rel="apple-touch-icon" sizes="76x76" href="pages/ico/76.png">#}
    {#    <link rel="apple-touch-icon" sizes="120x120" href="pages/ico/120.png">#}
    {#    <link rel="apple-touch-icon" sizes="152x152" href="pages/ico/152.png">#}
    {#    <link rel="icon" type="image/x-icon" href="favicon.ico"/>#}
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link href="{% static 'assets/plugins/pace/pace-theme-flash.css' %} " rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet" type="text/css"/>
    <link href="{% static 'pages/css/custom.css' %} " rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css"
          type="text/css">

    <link href="{% static 'assets/plugins/font-awesome/css/font-awesome.css' %} " rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/plugins/swiper/css/swiper.css' %} " rel="stylesheet" type="text/css" media="screen"/>

    <link class="main-stylesheet" href="{% static 'pages/css/pages.css' %} " rel="stylesheet" type="text/css"/>
    <link class="main-stylesheet" href="{% static 'pages/css/pages-icons.css' %} " rel="stylesheet" type="text/css"/>
</head>
<body class="pace-dark">

{% if not debug %}
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NCK9FJK" height="0" width="0"
                style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
{% endif %}

{% block nav %}{% endblock %}

<div class="page-wrappers">

    {% block content %}
    {% endblock %}

</div>

{% block footer %}
    {% include 'base/_footer.html' %}
{% endblock %}


<script src="{% static 'assets/plugins/pace/pace.min.js' %} " type="text/javascript"></script>
<script type="text/javascript" src="{% static 'pages/js/pages.image.loader.js' %} "></script>
<script type="text/javascript" src="{% static 'assets/plugins/jquery/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/plugins/swiper/js/swiper.jquery.min.js' %} "></script>
<script type="text/javascript" src="{% static 'assets/plugins/velocity/velocity.min.js' %} "></script>
<script type="text/javascript" src="{% static 'assets/plugins/velocity/velocity.ui.js' %} "></script>
<script type="text/javascript" src="{% static 'assets/plugins/jquery-unveil/jquery.unveil.min.js' %} "></script>
<script type="text/javascript" src="{% static 'pages/js/pages.frontend.js' %} "></script>
<script type="text/javascript" src="{% static 'assets/plugins/jquery-validation/js/jquery.validate.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/plugins/cookie-consent-bar-message/dist/jquery.cookieMessage.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/custom.js' %} "></script>

{% block scripts %}





{% endblock %}
<script>
    $(document).ready(function () {
        $.cookieMessage({

            'mainMessage': "This website uses cookies. By using this website you consent to our use of these cookies. " +
                "For more information visit our <a href='/terms-condition-privacy'>Privacy Policy</a>. ",
            'acceptButton': 'Got It!',
            expirationDays: 20,
            cookieName: 'cookieMessage',
            backgroundColor: '#1a1a1a',
            fontSize: '14px',
            fontColor: 'white',
            btnBackgroundColor: '#007bff',
            btnFontSize: '11px',
            btnFontColor: 'white',
            linkFontColor: '#3a8fc8'
        });
    });
</script>
</body>
</html>

templates/base/contact.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Contact us{% endblock %}
{% block metatitle %}Contact us Form{% endblock %}
{% block metadescription %}Do you have a question, feature request or similar? Contact us{% endblock %}

{% block nav %}
    {% include 'base/_nav.html' %}
{% endblock %}

{% block content %}
    {% include "base/_small_header.html" %}
    {% include "account/_tabs.html" %}

    <section class="m-t-40 sm-m-t-30">

        <section class="p-b-10">
            <div class="container">
                <div class="">
                    <h1 class="text-center">Contact us!</h1>
                </div>
            </div>
        </section>

        <section class="p-b-40">
            <div class="container">
                <div class="m-b-30 with-border padding-20 col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
                    <p class="m-b-45">Do you have a question, feature request or similar? Contact us. We want feedback
                        :)</p>

                    <form method="POST" id="contact-form" novalidate>
                        <div class="form-group">

                            {% include 'base/_messages.html' %}

                            {% if form %}
                                {% csrf_token %}

                                <div class="form-group form-group-default required">
                                    <label class="control-label" for="id_from_email">Your email</label>
                                    {{ form.from_email|add_class:'form-control' }}
                                </div>

                                <div class="form-group form-group-default">
                                    <label class="control-label" for="id_subject">Your subject</label>
                                    {{ form.subject|add_class:'form-control' }}
                                </div>

                                <div class="form-group form-group-default required">
                                    <label class="control-label" for="id_message">Message</label>
                                    {{ form.message|add_class:'form-control height-150' }}
                                </div>

                                {{ form.captcha }}

                                <div class="m-t-20">
                                    <button class="btn btn-primary m-r-75" type="submit">Save</button>
                                </div>
                            {% endif %}

                        </div>
                    </form>

                </div>
            </div>
        </section>

    </section>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            {#$('#contact-form').validate();#}
        });
    </script>
{% endblock %}

templates/base/contact_success.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Contact Success{% endblock %}
{% block metatitle %}Contact Success{% endblock %}
{% block metadescription %}Contact Success{% endblock %}

{% block nav %}
    {% include 'base/_nav.html' %}
{% endblock %}

{% block content %}
    {% include "base/_small_header.html" %}
    {# {% include "account/_tabs.html" %}#}

    <section class="m-t-40 sm-m-t-30">

        <section class="p-b-10">
            <div class="container">
                <div class="">
                    <h1 class="text-center">Contact Success</h1>
                </div>
            </div>
        </section>

        <section class="p-b-40">
            <div class="container">
                <div class="text-center m-b-30 with-border padding-20 col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">

                    <p>Thanks for your message. We'll contact you soon as possible.</p>

                </div>
            </div>
        </section>

    </section>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
        });
    </script>
{% endblock %}

templates/base/what.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load mathfilters %}

{% block title %}What{% endblock %}
{% block metatitle %}What{% endblock %}
{% block metadescription %}
    You wish a simple website monitoring? You're in the right place here. If the website encountering a problem,
    you'll be notified via email immediately. SSL-Certificate problems will be monitored too. You'll get notified not
    only when the website is down, you'll notified also when the sites returns any 4xx/5xx HTTP-Status code.
{% endblock %}

{% block nav %}
    {% include 'base/_nav.html' %}
{% endblock %}

{% block content %}
    {% include "base/_small_header.html" %}
    {# {% include "account/_tabs.html" %}#}

    <section class="m-t-40 sm-m-t-30">

        <section class="p-b-10">
            <div class="container">
                <div class="">
                    <h1 class="text-center">What</h1>
                </div>
            </div>
        </section>

        <section class="p-b-40">
            <div class="container">
                <div class="m-b-30 with-border padding-20 col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">

                    <p>You wish a simple website monitoring? You're in the right place here. We provide a simple Website
                        monitoring (Server IPv6/IPv6 coming soon).</p>
                    <p>If the website encountering a problem, you'll be notified via email immediately. You'll get
                        notified not only when the website is down, you'll notified also when the sites returns any
                        4xx/5xx HTTP-Status code. Sure, SSL-Certificate problems will be also monitored. Join the
                        simplest website monitoring tool <a href="{% url 'account_signup' %}">here</a>.
                    </p>
                    <div class="m-t-55">
                        <div class="">
                            <h6 class="block-title">How it works?</h6>
                            <p class="hint-text">You create a new monitoring for each site and you set the check
                                interval (from minute to day). You can also set the interval of the reminder when a site
                                is down. You'll be informed then, e.g. all 3h via email that the problem still
                                exists.</p>
                        </div>

                        <div class="m-t-35">
                            <h6 class="block-title">Which intervals can I set for checks and reminder?</h6>
                            <p class="hint-text"><i>Check interval:</i><br/> For Pro Plan: The smallest interval is
                                <b>all 5 minutes to days.</b><br/> For Basic Plan: The smallest interval
                                is all {{ BASIC_PLAN_MIN_PERIOD_CHECK_MINUTES|intdiv:60 }} hours to days.</p>

                            <p class="hint-text"><i>Reminder interval:</i> <br/>

                                For Pro Plan: The smallest interval <b>all 30 minutes to days.</b><br/>
                                For Basic Plan: The smallest interval
                                is {{ BASIC_PLAN_MIN_WHEN_OFFLINE_SEND_NEXT_MINUTES|intdiv:60 }} hours to days.
                                <br/>
                            </p>
                            <p class="hint-text">The reminder can also be deactivated on both plans.
                            </p>
                        </div>

                        <div class="m-t-35">
                            <h6 class="block-title">What are reminders?</h6>
                            <p class="hint-text">When a site has a problem, you'll get notified via email. After the
                                first email, you can be notified again. You can set a reminder which inform you again
                                after some time (depends on the reminder interval) if the website still has a problem.
                                The reminder can also be deactivated.</p>
                        </div>

                        <div class="m-t-35">
                            <h6 class="block-title">How I get informed?</h6>
                            <p class="hint-text">You'll be informed via email.</p>
                        </div>
                        <div class="m-t-35">
                            <h6 class="block-title">Can I set multiple email addresses?</h6>
                            <p class="hint-text">Yes, you can add multiple email addresses. All these email addresses
                                will be used for notifications. See <a href="/#price">Pricing</a> for the number of
                                email addresses.</p>
                        </div>

                        <div class="m-t-35">
                            <h6 class="block-title">Which errors will I be informed about?</h6>
                            <p class="hint-text">Generally, when the site is unreachable (offline), all 4xx and 5xx
                                HTTP-Statuscodes and SSL-Certificate Error (invalid, expired). Do you need another
                                error-alert? <a href="{% url 'contact' %}">Contact us!</a></p>
                        </div>

                        <div class="m-t-35">
                            <h6 class="block-title">Can I monitor also Servers?</h6>
                            <p class="hint-text">Currently not. But this feature is on our To-Do list. Soon you will
                                also
                                be able to monitor IPv4/IPv6</p>
                        </div>

                        <div class="m-t-35">
                            <h6 class="block-title">The Basic Plan limits my active websites checks. Can I still add
                                more websites?</h6>
                            <p class="hint-text">If you have Basic Plan, you can add more
                                than {{ BASIC_PLAN_MAX_ACTIVE_CHECKS }} websites. These will be inactive.</p>
                        </div>

                        <div class="m-t-35">
                            <h6 class="block-title">How works the payment for Pro Plan?</h6>
                            <p class="hint-text">We use <a target="_blank" href="http://stripe.com">Stripe</a> Checkout.
                                Of course we do not collect credit card information.</p>
                            <p>Before the subscription expires after a year, you'll notified early to renew the
                                subscription. But we do not automatically renew the subscription in your favour.</p>
                        </div>

                        <div class="m-t-35">
                            <h6 class="block-title">Where is this website and where are the data hosted?</h6>
                            <p class="hint-text">In USA.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </section>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
        });
    </script>
{% endblock %}