check/urls.py
from django.urls import path
from .views import show_check, create_check, update_check, delete_check, debug

urlpatterns = [
    path('overview', show_check, name='show_check'),
    path('new', create_check, name='create_check'),
    path('update/<int:id>/', update_check, name='update_check'),
    path('delete/<int:id>/', delete_check, name='delete_check'),

    path('debug', debug, name='debug'),

]

siteisrunning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from siteisrunning.views import redirect_view, term_condition_privacy, contact, home, what

urlpatterns = [
    path('admin/', admin.site.urls),
    path('redirect/', redirect_view),

    # path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('payment.urls')),

    path('', home, name='home'),
    path('websites/', include('check.urls')),
    path('terms-condition-privacy/', term_condition_privacy, name='term_condition_privacy'),
    path('contact/', contact, name='contact'),
    path('what/', what, name='what'),

    path('robots.txt/', TemplateView.as_view(template_name='base/robots.txt', content_type='text/plain'),
         name='robots'),

]

check/models.py
import datetime

from django.db import models
from django.utils import timezone

from users.models import CustomUser


class Check(models.Model):
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=255)
    description = models.TextField(blank=True)
    url = models.URLField('Website/Server', max_length=255)
    active = models.BooleanField()
    online = models.BooleanField(default=True)
    period_check = models.PositiveIntegerField()
    when_offline_period_send_mail = models.PositiveIntegerField()
    offline_last_mail_sent = models.DateTimeField(null=True,
                                                  blank=True,
                                                  help_text="If offline and mail was sent. Empty if site is online.")
    checked_at = models.DateTimeField()
    created_at = models.DateTimeField()  # Auto add is bad
    updated_at = models.DateTimeField()  # Auto add is bad

    @staticmethod
    def is_down(status):
        if not status:
            return True
        elif str(status).startswith('4') or str(status).startswith('5'):
            return True
        elif status == 'SSLCert':
            return True
        elif status == 'ConnectionRefused':
            return True
        elif status == 'TimeoutError':
            return True
        elif status == 'ConnectionAbortedError':
            return True
        elif status == 'ConnectionAborted':
            return True
        elif status == 'ConnectionResetError':
            return True
        elif status == 'ConnectionError':
            return True

        return False

    def time_to_check(self):
        next_check = self.checked_at + datetime.timedelta(minutes=self.period_check)

        # Time passed?
        if next_check <= timezone.now():
            return True
        else:
            return False

    def time_to_send_mail(self):
        # If not set, this means its the first email which will be sent
        if not self.offline_last_mail_sent:
            return True

        next_mail = self.offline_last_mail_sent + datetime.timedelta(minutes=self.when_offline_period_send_mail)

        # Time passed?
        if next_mail <= timezone.now():
            # If set 0, user doesn't want more emails
            if self.when_offline_period_send_mail == 0:
                return False

            return True
        else:
            return False

check/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

from .models import Check


class CheckForm(forms.ModelForm):
    active = forms.BooleanField(initial=1, required=0)
    name = forms.CharField(required=1, widget=forms.Textarea(attrs={'placeholder': 'MyName/Customer name'}))
    description = forms.CharField(required=0, widget=forms.TextInput(attrs={'placeholder': 'Optional description'}))
    url = forms.URLField(required=1, widget=forms.URLInput(attrs={'placeholder': 'http:// or https://'}))

    period_check = forms.IntegerField(min_value=5, max_value=43200, initial=60)
    when_offline_period_send_mail = forms.IntegerField(min_value=0, max_value=43200, initial=0)

    checked_at = forms.DateTimeField(initial=timezone.now(), disabled=1)
    created_at = forms.DateTimeField(initial=timezone.now(), disabled=1)
    updated_at = forms.DateTimeField(initial=timezone.now(), disabled=1)

    class Meta:
        model = Check
        fields = ['name', 'url', 'description', 'active', 'period_check', 'when_offline_period_send_mail',
                  'checked_at', 'created_at', 'updated_at']

check/views.py
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from check.forms import CheckForm
from check.models import Check
from payment.models import Payment
from siteisrunning.settings import BASIC_PLAN_MIN_PERIOD_CHECK_MINUTES, BASIC_PLAN_MIN_WHEN_OFFLINE_SEND_NEXT_MINUTES
import datetime


def debug(request):
    a = 1


@login_required
def show_check(request):
    user = request.user
    checks = Check.objects.filter(owner=request.user)
    disabled_html_class = 'disabled'
    if Payment.allowed_add_more_checks(user):
        disabled_html_class = ''

    return render(request, 'show.html', {'checks': checks, 'user': user, 'disabled_html_class': disabled_html_class})


@login_required
def create_check(request):
    user = request.user
    if not Payment.allowed_add_more_checks(user):
        messages.error(request,
                       'You use Basic Plan. You can have max. 4 active Checks. Upgrade to Pro under "Account" Tab')
        return redirect(show_check)

    form = CheckForm(request.POST or None)

    if form.is_valid():
        form_data = form.save(commit=False)
        form_data.owner = request.user
        form_data.created_at = timezone.now()
        form_data.updated_at = timezone.now()
        form_data.checked_at = timezone.now() - datetime.timedelta(
            days=50)  # Ensure next check will be triggered at next cron

        check = form.save()

        if not Payment.is_user_paying(request.user):
            _basic_plan_downgrade(check, request)
        else:
            if not check.when_offline_period_send_mail == 0 and form_data.when_offline_period_send_mail < 30:
                check.when_offline_period_send_mail = 30
                messages.success(request, '"When offline, send next mail all" set to minimum 30 minutes.')
                check.save()

        if not Payment.allowed_add_more_checks(request.user):
            _basic_plan_ensure_max_checks(check, request)

        messages.success(request,
                         'New Website Check created successfully. Be aware: The first check will be in few minutes.')
        return redirect('show_check')

    return render(request, 'create_form.html', {'form': form, 'title_prefix': 'Create'})


@login_required
def update_check(request, id):
    check = Check.objects.get(id=id)
    if check.owner != request.user:
        raise PermissionDenied('Not Found')

    form = CheckForm(request.POST or None, instance=check)

    if form.is_valid():
        form_data = form.save(commit=False)
        form_data.updated_at = timezone.now()
        form_data.checked_at = timezone.now() - datetime.timedelta(
            days=50)  # Ensure next check will be triggered at next cron

        check = form.save()

        if not Payment.is_user_paying(request.user):
            _basic_plan_downgrade(check, request)
        else:
            if not check.when_offline_period_send_mail == 0 and form_data.when_offline_period_send_mail < 30:
                check.when_offline_period_send_mail = 30
                messages.success(request, '"When offline, send next mail all" set to minimum 30 minutes.')
                check.save()

        if not Payment.allowed_add_more_checks(request.user):
            _basic_plan_ensure_max_checks(check, request)

        messages.success(request, 'Website Check edited successfully. Be aware: The next check will be in few minutes.')
        return redirect('show_check')

    return render(request, 'create_form.html', {'form': form, 'check': check, 'title_prefix': 'Edit'})


def _basic_plan_downgrade(check, request):
    if check.period_check < BASIC_PLAN_MIN_PERIOD_CHECK_MINUTES:
        check.period_check = BASIC_PLAN_MIN_PERIOD_CHECK_MINUTES
        messages.error(request,
                       'You use Basic Plan. Your minimum period check is 4h. Upgrade to Pro under "Account" Tab')

    if not check.when_offline_period_send_mail == 0 and check.when_offline_period_send_mail < BASIC_PLAN_MIN_WHEN_OFFLINE_SEND_NEXT_MINUTES:
        check.when_offline_period_send_mail = BASIC_PLAN_MIN_WHEN_OFFLINE_SEND_NEXT_MINUTES
        messages.error(request,
                       'You use Basic Plan. Your minimum reminder period is 8h. Upgrade to Pro under "Account" Tab')

    check.save()


def _basic_plan_ensure_max_checks(check, request):
    if check.active:
        check.active = False
        messages.error(request,
                       'You use Basic Plan. You can have max. 4 active Checks. Upgrade to Pro under "Account" Tab')
        check.save()


@login_required
def delete_check(request, id):
    check = Check.objects.get(id=id)
    if check.owner != request.user:
        raise PermissionDenied('Not Found')

    if request.method == 'POST':
        check.delete()
        messages.success(request, 'Website Check deleted successfully')
        return redirect('show_check')

    return render(request, 'delete_confirm.html', {'check': check})

check/templates/create_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}{{ title_prefix }}{% endblock %}
{% block metatitle %}{ title_prefix }} website{% endblock %}
{% block metadescription %}{ title_prefix }} an website check and save it.{% endblock %}

{% block nav %}
    {% include 'base/_nav.html' %}
{% endblock %}

{% block content %}
    {% include "base/_small_header.html" %}
    {% include "account/_tabs.html" %}

    <section class="m-t-40 sm-m-t-30">

        <section class="p-b-10">
            <div class="container">
                <div class="">
                    <h1 class="text-center">{{ title_prefix }} website</h1>
                </div>
            </div>
        </section>

        <section class="p-b-40">
            <div class="container">
                <div class="m-b-30 with-border padding-20 col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">

                    <form method="POST" id="create-edit-form" class="">
                        <div class="form-group">

                            {% include 'base/_messages.html' %}
                            {% csrf_token %}

                            <div class="form-group form-group-default required">
                                <label class="control-label" for="id_name">Name</label>
                                {{ form.name|add_class:'form-control' }}
                            </div>

                            <div class="form-group form-group-default">
                                <label class="control-label" for="id_description">Description</label>
                                {{ form.description|add_class:'form-control' }}
                            </div>

                            <div class="form-group form-group-default required">
                                <label class="control-label" for="id_url">URL</label>
                                {{ form.url|add_class:'form-control' }}
                            </div>

                            <div class="form-group form-group-default required">
                                <label class="control-label" for="id_period_check">Check all</label>
                                {{ form.period_check }}<span>&nbsp;minutes</span>
                                <div class="fs-13">1 day = 1440 minutes, 2 day = 2880 minutes, 3 day = 4320
                                    minutes
                                </div>
                            </div>

                            <div class="form-group form-group-default required">
                                <label class="control-label" for="id_when_offline_period_send_mail">When offline, send
                                    reminder all</label>
                                {{ form.when_offline_period_send_mail }}<span>&nbsp;minutes</span>
                                <div class="fs-13">When the site/server is offline and you've been already
                                    been informed the first time, at what interval do you want to be informed again?
                                    <br/>
                                    <br/>Set 0 if you don't want to receive any further notifications after the first
                                    mail.
                                </div>
                            </div>

                            <div class="checkbox check-success">
                                {{ form.active }}
                                <label class="control-label" for="id_active">Active</label>
                            </div>
                            <div class="m-t-20">
                                <button class="btn btn-primary m-r-75" type="submit">Save</button>

                                {% if check %}
                                    <a class="btn btn-danger text-light"
                                       href="{% url 'delete_check' check.id %}">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </section>

    </section>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#create-edit-form').validate();
        });
    </script>
{% endblock %}

check/templates/delete_confirm.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block title %}Delete{% endblock %}
{% block metatitle %}Delete Check{% endblock %}
{% block metadescription %}Delete an website check and save it.{% endblock %}

{% block nav %}
    {% include 'base/_nav.html' %}
{% endblock %}

{% block content %}
    {% include "base/_small_header.html" %}
    {% include "account/_tabs.html" %}

    <section class="m-t-40 sm-m-t-30">

        <section class="p-b-10">
            <div class="container">
                <div class="">
                    <h1 class="text-center">Delete Website Check</h1>
                </div>
            </div>
        </section>

        <section class="p-b-40">
            <div class="container">
                <div class="m-b-30 with-border padding-20 text-center">

                    <form method="POST">
                        {% csrf_token %}
                        <p class="fs-18">Are you sure to delete {{ check.name }}?</p>
                        <button class="m-t-15 btn btn-danger" type="submit">DELETE</button>
                    </form>

                </div>
            </div>
        </section>

    </section>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#create-edit-form').validate();
        });
    </script>
{% endblock %}

check/templates/show.html
{% extends 'base/base.html' %}

{% block title %}Overview{% endblock %}
{% block metatitle %}Overview{% endblock %}
{% block metadescription %}Overview of your websites{% endblock %}

{% block nav %}
    {% include 'base/_nav.html' %}
{% endblock %}

{% block content %}
    {% include "base/_small_header.html" %}
    {% include "account/_tabs.html" %}


    <section class="m-t-40 sm-m-t-30">

        <section class="">
            <div class="container">

                <div class="">
                    {% include 'base/_messages.html' %}
                    <h1 class="text-center ">Overview</h1>
                </div>
            </div>
        </section>

        <section class="p-b-40 ">
            <div class="container">
                <div class="m-b-30 with-border padding-20 col-xs-12 col-md-10 col-md-offset-1">

                    <a href="{% url 'create_check' %}" class="m-b-25 btn btn-primary {{ disabled_html_class }}">Add
                        new</a>

                    {% if not user.is_paying %}
                        <a href="{% url 'checkout_account' %}" class="m-b-25 m-l-50 btn btn-danger">Add
                            Pro Plan (25$/y)</a>
                    {% endif %}

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>URL</th>
                                <th>Status</th>
                                <th>Active</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for check in checks %}
                                {% if check.active %}
                                    {% if check.online %}
                                        {% with statusclass="success" %}
                                            <tr class="{{ statusclass }}">
                                        {% endwith %}
                                    {% else %}
                                    {% with statusclass="danger" %}
                                        <tr class="{{ statusclass }}">
                                    {% endwith %}
                                    {% endif %}
                                {% else %}
                                {% with statusclass="active" %}
                                    <tr class="{{ statusclass }}">
                                {% endwith %}
                                {% endif %}

                            <td><a href="{% url 'update_check' check.id %}">{{ check.name }} </a></td>
                            <td>{{ check.url }}</td>
                            <td>{% if check.online %} Online {% else %} Offline {% endif %}</td>
                            <td>{% if check.active %} Active {% else %} Disabled {% endif %}</td>

                            </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                    </div>
                </div>

            </div>
        </section>

    </section>
{% endblock %}